### ISSUE TITLE
GPU Support

### ISSUE THREAD

**Issue by okpatil4u** [wozeparrot/tinyrwkv#1]
Hello @wozeparrot , thanks for this amazing repo. This is a great learning experience.

How would I port this to GPU ? I understand that GPU is supported in TinyGrad, either through Cuda or OpenCL. What should I change to get this code working on GPU ?

**Comment by wozeparrot** [comment]
To get it working on GPU all you should need to do is to run it with the environment variable `GPU` set to 1.

Like, `GPU=1 python main.py gen`

I do find that I don't get the best performance that way, probably need some more optimization.
For me, its faster if you run with llvm instead: `LLVM=1 LLVMOPT=1 python main.py gen`

**Comment by okpatil4u** [comment]
Thanks ! Closing this issue.
